### ISSUE TITLE
Failed to add reference to 'pdfium' when installing

### ISSUE THREAD

**Issue by dpdev22** [VerifyTests/Verify.Syncfusion#1]
We would like to use **Verify.Syncfusion** in our unit test as we have a Syncfusion license. When installing the Nuget package to the test project, it doesn't complete the installation process and returns the following message to the Error List window of Visual Studio.

> Failed to add reference to 'pdfium'. Please make sure that the file is accessible, and that it is a valid assembly or COM component.

The version of .Net Framework used by the project is 4.8. I also tried installing it on a fresh project and the same error message was returned. Could you provide us with information on what's causing the error and how to solve it?

Thanks in advance for the help.

**Comment by SimonCropp** [comment]
does it work if u manually add the reference to the csproj?

if not i think you should raise this with the VS team
