### ISSUE TITLE
Render Word documents as images

### ISSUE THREAD

**Issue by steingran** [VerifyTests/Verify.Syncfusion#47]
#### Is the feature request related to a problem

I notice the VerifySyncFusion_Word.cs extracts text only and not a screenshot of the Word document, as the VerifySyncFusion_Pdf.cs class does. Ref https://github.com/VerifyTests/Verify.Syncfusion/blob/main/src/Verify.Syncfusion/VerifySyncfusion_Word.cs#L51. 

#### Describe the solution

Using the DocIORenderer class from the Syncfusion.DocIORenderer.Net.Core nuget it is possible to render Word documents as images, and I would be happy to create a PR for this.

#### Describe alternatives considered

Would be great if most (or all) of the VerifySyncFusion*-classes both extracted text and images/screenshots of the documents that are verified

#### Additional context

As mentioned above, I would be happy to contribute a PR with the changes suggested above

**Comment by SimonCropp** [comment]
happy to accept a PR for this
